"""
Handle data file uploads and provide a tabular preview interface.

This module provides a UI for administrators to upload new CSV or Excel
datasets. It parses the uploaded files in memory and displays a preview
using a Dash DataTable to ensure data integrity before database insertion.
"""

import dash
from dash import html, dcc, callback, Input, Output, State, dash_table
import dash_bootstrap_components as dbc
import pandas as pd
import base64
import io

# Register this page with the Dash app
dash.register_page(__name__, name='Data Management')

# ==========================================
# Page Layout
# ==========================================
layout = html.Div([
    # Row 1: Header
    dbc.Row([
        dbc.Col([
            html.H2("Data Management Console", className="mb-2"),
            html.P(
                "Upload new tourism data files (CSV or Excel) to update the database. "
                "The system will preview the first few rows to ensure data integrity before committing.",
                className="text-muted mb-4"
            )
        ])
    ]),

    # Row 2: Upload Component
    dbc.Row([
        dbc.Col(
            dbc.Card(
                dbc.CardBody([
                    html.H5("Upload New Dataset", className="card-title mb-3"),
                    
                    # Drag and Drop Upload Component
                    dcc.Upload(
                        id='datamanager-upload-data',
                        children=html.Div([
                            'Drag and Drop or ',
                            html.A('Select Files', className="text-primary font-weight-bold")
                        ]),
                        style={
                            'width': '100%',
                            'height': '120px',
                            'lineHeight': '120px',
                            'borderWidth': '2px',
                            'borderStyle': 'dashed',
                            'borderRadius': '10px',
                            'textAlign': 'center',
                            'margin': '10px 0',
                            'backgroundColor': '#f8f9fa', # Light grey background
                            'cursor': 'pointer'
                        },
                        # Allow multiple files to be uploaded (set to False for strictly one file at a time)
                        multiple=False 
                    ),
                    
                    # Placeholder for status messages (e.g., success or error)
                    html.Div(id='datamanager-upload-status', className="mt-3")
                ]),
                className="shadow-sm border-0 mb-4"
            ),
            width=12
        )
    ]),

    # Row 3: Data Preview Section
    dbc.Row([
        dbc.Col(
            dbc.Card(
                dbc.CardBody([
                    html.H5("Data Preview", className="card-title mb-3"),
                    # Placeholder for the data table generated by the callback
                    html.Div(id='datamanager-output-data-upload')
                ]),
                className="shadow-sm border-0"
            ),
            width=12
        )
    ])
])

# ==========================================
# Helper Function for File Parsing
# ==========================================
def parse_contents(contents, filename):
    """
    Decodes the uploaded file and converts it into a pandas DataFrame.
    Returns a Dash DataTable component containing a preview of the data.
    """
    # Dash uploads files as base64 encoded strings
    content_type, content_string = contents.split(',')
    decoded = base64.b64decode(content_string)
    
    try:
        # Check the file extension and read accordingly
        if 'csv' in filename:
            # Assume that the user uploaded a CSV file
            df = pd.read_csv(io.StringIO(decoded.decode('utf-8')))
        elif 'xls' in filename:
            # Assume that the user uploaded an Excel file
            df = pd.read_excel(io.BytesIO(decoded))
        else:
            return html.Div([
                dbc.Alert("Unsupported file format. Please upload a CSV or Excel file.", color="danger")
            ])
            
    except Exception as e:
        # Handle exceptions (e.g., corrupted file, wrong encoding)
        print(e)
        return html.Div([
            dbc.Alert(f"There was an error processing this file: {str(e)}", color="danger")
        ])

    # If successful, return a preview table (top 5 rows) and info
    return html.Div([
        html.H6(f"File: {filename} (Previewing first 5 rows)"),
        
        # Dash DataTable for clean, interactive tabular display
        dash_table.DataTable(
            data=df.head().to_dict('records'),
            columns=[{'name': i, 'id': i} for i in df.columns],
            style_table={'overflowX': 'auto'}, # Enable horizontal scroll if many columns
            style_cell={
                'textAlign': 'left',
                'padding': '10px',
                'fontFamily': 'sans-serif'
            },
            style_header={
                'backgroundColor': '#2C3E50',
                'color': 'white',
                'fontWeight': 'bold'
            }
        ),
        
        html.Hr(),
        dbc.Button("Commit to Database", color="success", className="mt-2") # Mock button for future backend integration
    ])

# ==========================================
# Callbacks (Interactivity / Logic)
# ==========================================
@callback(
    [Output('datamanager-output-data-upload', 'children'),
     Output('datamanager-upload-status', 'children')],
    [Input('datamanager-upload-data', 'contents')],
    [State('datamanager-upload-data', 'filename')]
)
def update_output(contents, filename):
    """
    Triggered when a user uploads a file. 
    Calls parse_contents to generate the table and updates status.
    """
    if contents is not None:
        # File uploaded successfully
        preview_table = parse_contents(contents, filename)
        status_msg = dbc.Alert(f"Successfully loaded {filename} into memory.", color="success", duration=4000)
        return preview_table, status_msg
    
    # Default state before any upload
    return html.Div("No data uploaded yet. Please use the drag-and-drop box above."), ""